language: node_js
env:
  -GH_TOKEN=jf24FAI9y445rRV9cIilNA
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages
    on:
      branch: v1
  - skip_cleanup: true
    provider: script
    script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "v1" && "$TRAVIS_BRANCH" != "gh-pages"'
