openapi: 3.0.0
info:
  version: 1.0.0
  title: webfont api
  termsOfService: 'https://webfont.io'
  contact:
    email: mail.webfont.io@gmail.com
    url: 'https://webfont.io/'
  license:
    name: GNU
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: >

    # 简介

    webfont.io 是专注于在网页上显示子集化字体的项目，


    # api 详情

    The goal of The OpenAPI Specification is to define a standard,
    language-agnostic interface to REST APIs which

    allows both humans and computers to discover and understand the capabilities
    of the service without access to source

    code, documentation, or through network traffic inspection. When properly
    defined via OpenAPI, a consumer can 

    understand and interact with the remote service with a minimal amount of
    implementation logic. Similar to what

    interfaces have done for lower-level programming, OpenAPI removes the
    guesswork in calling the service.
externalDocs:
  description: webfont官方网站
  url: 'https://webfont.io/'
tags:
  - name: Echo
    description: Example echo operations
  - name: User
    description: Operations about user
servers:
  - url: 'http://webfont.apiatm.com/v1'
  - url: 'https://webfont.apiatm.com/v1'
