openapi: 3.0.0
info:
  version: 1.0.0
  title: webfont api
  termsOfService: 'https://webfont.io'
  contact:
    email: mail.webfont.io@gmail.com
    url: 'https://webfont.io/'
  x-logo:
    url: logo.png
  description: >
    webfont项目 隶属于[apiatm商业联盟](https://www.apiatm.com),联盟下有以下项目推荐：


    - [webfont.io 子集化](http://webfont.io/) 将原本需要10MB的字体，按需求分割成几十 至 几百kb的(ttf eot
    woff woff2)

    - [youziku.com 在线图片生成](http://youziku.com/) 在线字体转图片工具，以及碎片化字体授权。

    # 简介

    webfont.io 是专注于在网页上显示子集化字体的项目，将原本需要10MB的字体，按需求分割成几十 至 几百kb

    webfont生成格式：ttf eot woff woff2
servers:
  - url: 'http://webfont.apiatm.com/v1'
  - url: 'https://webfont.apiatm.com/v1'
